#https://docs.travis-ci.com/user/reference/overview/
language: java
dist: trusty
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
jdk:
- oraclejdk8
- oraclejdk11
- openjdk11
script:
- java -version
- mvn install
